### ISSUE TITLE
HDRP Volume Profile Locked

### ISSUE THREAD

**Issue by ArieLeo** [Milk-Drinker01/Milk_Instancer01#1]
Out of curiosity, why the instancer component override hdrp volume profile?

**Comment by Milk-Drinker01** [comment]
Im not quite sure what you mean here, off the top of my head the only thing related to the volume within the instancer itself, is when the instancer uses the volume profile to fetch the max shadow distance. do you mind providing more details?

**Comment by Milk-Drinker01** [comment]
I have pinned down and corrected this issue. It will be fixed with the next version, which will also be a major update

**Comment by Milk-Drinker01** [comment]
i forgot to close this issue when i released the update

**Comment by ArieLeo** [comment]
> I have pinned down and corrected this issue. It will be fixed with the next version, which will also be a major update

Glad you find, the issue. Sorry i forgot to check my github notification
