### ISSUE TITLE
Support for Instanced Stereo rendering

### ISSUE THREAD

**Issue by HeadClot** [Milk-Drinker01/Milk_Instancer01#4]
Hey @Milk-Drinker01 - Would it be possible to get support for [Single pass Instanced Stereo rendering](https://docs.unity3d.com/Manual/SinglePassInstancing.html) in Milk Instancer? 

So one draw call for both eyes. This is very important for devices such as the Meta Quest line of devices and PC VR headsets on lower end hardware.

**Comment by Milk-Drinker01** [comment]
Ive been working on this for the past few hours and would like to say that theres a 99% chance i can get this to work. ill try to have it working by the end of the day, along with URP support :)

**Comment by HeadClot** [comment]
Cool looking forward to it :)

**Comment by Milk-Drinker01** [comment]
I just pushed the single pass instanced support. ill ping u on discord when urp is ready. i got side tracked today fixing a few issues i noticed with the system and didnt get to it today
